from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("showcase/", views.showcase, name="showcase"),
    path("showcaseedited/<id>", views.showcaseedited, name="showcaseedited"),
    path("commssioningpage/", views.commssioningpage, name="commssioningpage"),
    path("tabletennis/", views.tabletennis, name="tabletennis"),
    path("reminder/", views.reminder, name="reminder"),
    path("oppor/", views.oppor, name="oppor"),
    path("cowritingoffers/", views.cowritingoffers, name="cowritingoffers"),
    path("cowritinglist/", views.cowritinglist, name="cowritinglist"),
    path("limitedrights/", views.limitedrights, name="limitedrights"),
    path("makeur/<commission_id>", views.makeur, name="makeur"),
    path("conversion_redirect/", views.conversion_redirect,
         name="conversion_redirect"),
    path("view/<commission_id>", views.commission_view, name="view"),
    path("shortlist2/<pk>", views.shortlist2, name="shortlist2"),
    path("shortlist/", views.shortlist, name="shortlist"),
    path("auction_success/", views.auction_success, name="auction_success"),
    path("auction_full_failed/", views.auction_full_failed,
         name="auction_full_failed"),
    path("auction_limited_failed/", views.auction_limited_failed,
         name="auction_limited_failed"),
    path("commission_success/", views.commission_success,
         name="commission_success"),
    path("commission_failed/", views.commission_failed, name="commission_failed"),
    # path("pageenter/",views.pageenter,name="pageener"),
    path(
        "delete_commission/<commission_id>",
        views.delete_commission,
        name="delete_commission",
    ),
    path("send_Bank_detail/", views.send_Bank_detail, name='send_Bank_detail'),
    path("message/", views.message, name='message'),
    path("messagecom/", views.messagecom, name='messagecom'),
    path(
        "mycommissionedprojects/",
        views.mycommissionedprojects,
        name="mycommissionedprojects",
    ),
    path("auctionpage/", views.auctionpage, name="auctionpage"),
    path("detailpage/<id>/", views.detailpage, name="detailpage"),
    path("showcaseupdate/<id>/", views.showcaseupdate, name="showcaseupdate"),
    # path("browse_div/", views.browse_div, name="browse_div"),
    path("browse/", views.browse, name="browse"),
    path("myauction/", views.myauction, name="myauction"),
    path("checknewbidReceived/", views.checknewbidReceived, name="checknewbidReceived"),
    path("history/<id>/", views.history, name="history"),
    path("auctiondetails/<id>/", views.auctiondetails, name="auctiondetails"),
    path(
        "sendmailcowriter/",
        views.sendmailcowriter,
        name="sendmailcowriter",
    ),
    path("sameauctioneer/<id>", views.sameauctioneer, name="sameauctioneer"),
    path("bidnow/", views.bidnow, name="bidnow"),
    path("mybid/", views.mybid, name="mybid"),
    path("emailtoauctioneer/", views.emailtoauctioneer, name="emailtoauctioneer"),
    path("datascript/", views.datascript, name="datascript"),
    path("emailfordownload/", views.emailfordownload, name="emailfordownload"),
    path("shortlistshow/<pk>", views.shortlistshow, name="shortlistshow"),
    path("shortlistauc/<pk>", views.shortlistauc, name="shortlistauc"),
    path("premisespool/", views.premisespool, name="premisespool"),
    path("likepremise/<pk>", views.likepremise, name="likepremise"),
    path("dormant/", views.dormant, name="dormant"),
    path("contact_premise/", views.contact_premise, name="contact_premise"),
    path("deleteauction/<id>", views.deleteauction, name="deleteauction"),
    path("rate_auction/", views.rate_auction, name="rate_auction"),
    path("auction_checkoutpage/", views.auction_checkoutpage,
         name="auction_checkoutpage"),
    path("customnda/<id>", views.customnda, name="customnda"),
    path("auctionurl/", views.auctionurl, name="auctionurl"),
    path("contactforcowriting/", views.contactforcowriting,
         name="contactforcowriting"),
    path("deletepremisespool/<id>", views.deletepremisepool,
         name="deletepremisespool"),
    path("editpremisespool/", views.editpremise, name="editpremisespool"),
    path("auctionCheckout/", views.auctionCheckout, name="auctionCheckout"),
    path("commissionCheckout/", views.commissionCheckout,
         name="commissionCheckout"),
    path(
        "paymentDonecomm_stripe/",
        views.paymentDonecomm_stripe,
        name="paymentDonecomm_stripe",
    ),
    path(
        "paymentDonecomm_RazorPay/",
        views.paymentDonecomm_RazorPay,
        name="paymentDonecomm_RazorPay",
    ),
    path(
        "paymentDoneauction_RazorPay",
        views.paymentDoneauction_RazorPay,
        name="paymentDoneauction_RazorPay",
    ),
    path(
        "paymentDoneauction_stripe/",
        views.paymentDoneauction_stripe,
        name="paymentDoneauction_stripe",
    ),
    path('fetch_from_blockchain',views.fetch_from_blockchain, name="fetch_from_blockchain"),
    path('blockchainpermit',views.blockchainpermit, name="blockchainpermit"),
    path('permission/<id>/',views.commisioner_response,name="commisioner_response"),
    path('verfyFromBlockchain/',views.verfyFromBlockchain,name="verfyFromBlockchain"),
    path('try1',views.try1,name="try1"),
]
